# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/adriano/.local/lib/python3.10/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/adriano/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/adriano/Área de Trabalho/concordo"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/adriano/Área de Trabalho/concordo"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/adriano/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/adriano/.local/lib/python3.10/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/adriano/Área de Trabalho/concordo/CMakeFiles" "/home/adriano/Área de Trabalho/concordo//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/adriano/Área de Trabalho/concordo/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named concordo

# Build rule for target.
concordo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 concordo
.PHONY : concordo

# fast build rule for target.
concordo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/concordo.dir/build.make CMakeFiles/concordo.dir/build
.PHONY : concordo/fast

src/Canal.o: src/Canal.cpp.o
.PHONY : src/Canal.o

# target to build an object file
src/Canal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/concordo.dir/build.make CMakeFiles/concordo.dir/src/Canal.cpp.o
.PHONY : src/Canal.cpp.o

src/Canal.i: src/Canal.cpp.i
.PHONY : src/Canal.i

# target to preprocess a source file
src/Canal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/concordo.dir/build.make CMakeFiles/concordo.dir/src/Canal.cpp.i
.PHONY : src/Canal.cpp.i

src/Canal.s: src/Canal.cpp.s
.PHONY : src/Canal.s

# target to generate assembly for a file
src/Canal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/concordo.dir/build.make CMakeFiles/concordo.dir/src/Canal.cpp.s
.PHONY : src/Canal.cpp.s

src/CanalTexto.o: src/CanalTexto.cpp.o
.PHONY : src/CanalTexto.o

# target to build an object file
src/CanalTexto.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/concordo.dir/build.make CMakeFiles/concordo.dir/src/CanalTexto.cpp.o
.PHONY : src/CanalTexto.cpp.o

src/CanalTexto.i: src/CanalTexto.cpp.i
.PHONY : src/CanalTexto.i

# target to preprocess a source file
src/CanalTexto.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/concordo.dir/build.make CMakeFiles/concordo.dir/src/CanalTexto.cpp.i
.PHONY : src/CanalTexto.cpp.i

src/CanalTexto.s: src/CanalTexto.cpp.s
.PHONY : src/CanalTexto.s

# target to generate assembly for a file
src/CanalTexto.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/concordo.dir/build.make CMakeFiles/concordo.dir/src/CanalTexto.cpp.s
.PHONY : src/CanalTexto.cpp.s

src/CanalVoz.o: src/CanalVoz.cpp.o
.PHONY : src/CanalVoz.o

# target to build an object file
src/CanalVoz.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/concordo.dir/build.make CMakeFiles/concordo.dir/src/CanalVoz.cpp.o
.PHONY : src/CanalVoz.cpp.o

src/CanalVoz.i: src/CanalVoz.cpp.i
.PHONY : src/CanalVoz.i

# target to preprocess a source file
src/CanalVoz.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/concordo.dir/build.make CMakeFiles/concordo.dir/src/CanalVoz.cpp.i
.PHONY : src/CanalVoz.cpp.i

src/CanalVoz.s: src/CanalVoz.cpp.s
.PHONY : src/CanalVoz.s

# target to generate assembly for a file
src/CanalVoz.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/concordo.dir/build.make CMakeFiles/concordo.dir/src/CanalVoz.cpp.s
.PHONY : src/CanalVoz.cpp.s

src/Concordo.o: src/Concordo.cpp.o
.PHONY : src/Concordo.o

# target to build an object file
src/Concordo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/concordo.dir/build.make CMakeFiles/concordo.dir/src/Concordo.cpp.o
.PHONY : src/Concordo.cpp.o

src/Concordo.i: src/Concordo.cpp.i
.PHONY : src/Concordo.i

# target to preprocess a source file
src/Concordo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/concordo.dir/build.make CMakeFiles/concordo.dir/src/Concordo.cpp.i
.PHONY : src/Concordo.cpp.i

src/Concordo.s: src/Concordo.cpp.s
.PHONY : src/Concordo.s

# target to generate assembly for a file
src/Concordo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/concordo.dir/build.make CMakeFiles/concordo.dir/src/Concordo.cpp.s
.PHONY : src/Concordo.cpp.s

src/Mensagem.o: src/Mensagem.cpp.o
.PHONY : src/Mensagem.o

# target to build an object file
src/Mensagem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/concordo.dir/build.make CMakeFiles/concordo.dir/src/Mensagem.cpp.o
.PHONY : src/Mensagem.cpp.o

src/Mensagem.i: src/Mensagem.cpp.i
.PHONY : src/Mensagem.i

# target to preprocess a source file
src/Mensagem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/concordo.dir/build.make CMakeFiles/concordo.dir/src/Mensagem.cpp.i
.PHONY : src/Mensagem.cpp.i

src/Mensagem.s: src/Mensagem.cpp.s
.PHONY : src/Mensagem.s

# target to generate assembly for a file
src/Mensagem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/concordo.dir/build.make CMakeFiles/concordo.dir/src/Mensagem.cpp.s
.PHONY : src/Mensagem.cpp.s

src/Menus.o: src/Menus.cpp.o
.PHONY : src/Menus.o

# target to build an object file
src/Menus.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/concordo.dir/build.make CMakeFiles/concordo.dir/src/Menus.cpp.o
.PHONY : src/Menus.cpp.o

src/Menus.i: src/Menus.cpp.i
.PHONY : src/Menus.i

# target to preprocess a source file
src/Menus.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/concordo.dir/build.make CMakeFiles/concordo.dir/src/Menus.cpp.i
.PHONY : src/Menus.cpp.i

src/Menus.s: src/Menus.cpp.s
.PHONY : src/Menus.s

# target to generate assembly for a file
src/Menus.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/concordo.dir/build.make CMakeFiles/concordo.dir/src/Menus.cpp.s
.PHONY : src/Menus.cpp.s

src/Servidor.o: src/Servidor.cpp.o
.PHONY : src/Servidor.o

# target to build an object file
src/Servidor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/concordo.dir/build.make CMakeFiles/concordo.dir/src/Servidor.cpp.o
.PHONY : src/Servidor.cpp.o

src/Servidor.i: src/Servidor.cpp.i
.PHONY : src/Servidor.i

# target to preprocess a source file
src/Servidor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/concordo.dir/build.make CMakeFiles/concordo.dir/src/Servidor.cpp.i
.PHONY : src/Servidor.cpp.i

src/Servidor.s: src/Servidor.cpp.s
.PHONY : src/Servidor.s

# target to generate assembly for a file
src/Servidor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/concordo.dir/build.make CMakeFiles/concordo.dir/src/Servidor.cpp.s
.PHONY : src/Servidor.cpp.s

src/Sistema.o: src/Sistema.cpp.o
.PHONY : src/Sistema.o

# target to build an object file
src/Sistema.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/concordo.dir/build.make CMakeFiles/concordo.dir/src/Sistema.cpp.o
.PHONY : src/Sistema.cpp.o

src/Sistema.i: src/Sistema.cpp.i
.PHONY : src/Sistema.i

# target to preprocess a source file
src/Sistema.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/concordo.dir/build.make CMakeFiles/concordo.dir/src/Sistema.cpp.i
.PHONY : src/Sistema.cpp.i

src/Sistema.s: src/Sistema.cpp.s
.PHONY : src/Sistema.s

# target to generate assembly for a file
src/Sistema.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/concordo.dir/build.make CMakeFiles/concordo.dir/src/Sistema.cpp.s
.PHONY : src/Sistema.cpp.s

src/Usuario.o: src/Usuario.cpp.o
.PHONY : src/Usuario.o

# target to build an object file
src/Usuario.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/concordo.dir/build.make CMakeFiles/concordo.dir/src/Usuario.cpp.o
.PHONY : src/Usuario.cpp.o

src/Usuario.i: src/Usuario.cpp.i
.PHONY : src/Usuario.i

# target to preprocess a source file
src/Usuario.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/concordo.dir/build.make CMakeFiles/concordo.dir/src/Usuario.cpp.i
.PHONY : src/Usuario.cpp.i

src/Usuario.s: src/Usuario.cpp.s
.PHONY : src/Usuario.s

# target to generate assembly for a file
src/Usuario.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/concordo.dir/build.make CMakeFiles/concordo.dir/src/Usuario.cpp.s
.PHONY : src/Usuario.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/concordo.dir/build.make CMakeFiles/concordo.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/concordo.dir/build.make CMakeFiles/concordo.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/concordo.dir/build.make CMakeFiles/concordo.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... concordo"
	@echo "... src/Canal.o"
	@echo "... src/Canal.i"
	@echo "... src/Canal.s"
	@echo "... src/CanalTexto.o"
	@echo "... src/CanalTexto.i"
	@echo "... src/CanalTexto.s"
	@echo "... src/CanalVoz.o"
	@echo "... src/CanalVoz.i"
	@echo "... src/CanalVoz.s"
	@echo "... src/Concordo.o"
	@echo "... src/Concordo.i"
	@echo "... src/Concordo.s"
	@echo "... src/Mensagem.o"
	@echo "... src/Mensagem.i"
	@echo "... src/Mensagem.s"
	@echo "... src/Menus.o"
	@echo "... src/Menus.i"
	@echo "... src/Menus.s"
	@echo "... src/Servidor.o"
	@echo "... src/Servidor.i"
	@echo "... src/Servidor.s"
	@echo "... src/Sistema.o"
	@echo "... src/Sistema.i"
	@echo "... src/Sistema.s"
	@echo "... src/Usuario.o"
	@echo "... src/Usuario.i"
	@echo "... src/Usuario.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

